import { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export const metadata: Metadata = {
    title: 'Privacy Policy - Fliphats',
    description: 'Privacy Policy for the Fliphats platform.',
};

export default function PrivacyPage() {
    return (
        <div className="min-h-screen bg-background">
            {/* Navigation Header */}
            <nav className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
                <div className="max-w-5xl mx-auto px-6 h-14 flex items-center justify-between">
                    <Link href="/login" className="flex items-center gap-2 text-sm font-medium text-muted-foreground transition-colors hover:text-primary">
                        <ArrowLeft className="h-4 w-4" />
                        Back to Login
                    </Link>
                    <div className="font-semibold text-sm">Fliphats Legal</div>
                </div>
            </nav>

            <div className="py-16 px-6 sm:px-10">
                <div className="max-w-3xl mx-auto">
                    <div className="text-center mb-16">
                        <h1 className="text-4xl font-bold tracking-tight mb-4">Privacy Policy</h1>
                        <p className="text-muted-foreground">Effective Date: January 25, 2026</p>
                    </div>

                    <div className="prose prose-zinc dark:prose-invert max-w-none space-y-12">
                        <section>
                            <h3>1. Introduction</h3>
                            <p>
                                Fliphats ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Fliphats. This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service") alongside our application, Fliphats. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
                            </p>
                            <p>
                                We value your trust and are dedicated to protecting your personal information. This policy outlines our practices regarding data collection, usage, and protection. We encourage you to read this policy carefully to understand our approach to privacy and how it affects you.
                            </p>
                            <p>
                                This expanded policy ensures we meet the rigorous standards expected by enterprise clients and international regulations, including GDPR, CCPA, and other relevant data protection laws.
                            </p>
                        </section>

                        <section>
                            <h3>2. Definitions and Key Terms</h3>
                            <p>
                                To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, they are strictly defined as:
                            </p>
                            <ul>
                                <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                                <li><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Fliphats, which is responsible for your information under this Privacy Policy.</li>
                                <li><strong>Country:</strong> where Fliphats or the owners/founders of Fliphats are based, in this case is Australia.</li>
                                <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the Fliphats Service to manage the relationships with your consumers or service users.</li>
                                <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Fliphats and use the services.</li>
                                <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                                <li><strong>Personnel:</strong> refers to those individuals who are employed by Fliphats or are under contract to perform a service on behalf of one of the parties.</li>
                                <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                                <li><strong>Service:</strong> refers to the service provided by Fliphats as described in the relative terms (if available) and on this platform.</li>
                                <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                                <li><strong>Website:</strong> Fliphats’s site, which can be accessed via this URL: fliphats.com</li>
                                <li><strong>You:</strong> a person or entity that is registered with Fliphats to use the Services.</li>
                            </ul>
                        </section>

                        <section>
                            <h3>3. Information We Collect</h3>
                            <p>
                                We collect information from you when you visit our service, register, place an order, subscribe to our newsletter, respond to a survey or fill out a form.
                            </p>
                            <ul>
                                <li>Name / Username</li>
                                <li>Phone Numbers</li>
                                <li>Email Addresses</li>
                                <li>Mailing Addresses</li>
                                <li>Job Titles</li>
                                <li>Billing Addresses</li>
                                <li>Debit/credit card numbers</li>
                                <li>Password</li>
                                <li>Workspace preferences and settings</li>
                            </ul>
                            <p>
                                We also collect information from mobile devices for a better user experience, although these features are completely optional:
                            </p>
                            <ul>
                                <li><strong>Location (GPS):</strong> Location data helps to create an accurate representation of your interests, and this can be used to bring more targeted and relevant ads to potential customers.</li>
                                <li><strong>Phonebook (Contacts list):</strong> Your contacts list allows the Service to be much more easy to use by the user, since accessing your contacts from the app makes you save tons of time.</li>
                                <li><strong>Camera (Pictures):</strong> Granting camera permission allows the user to upload any picture straight from the Service, you can safely deny camera permissions for this Service.</li>
                                <li><strong>Photo Gallery (Pictures):</strong> Granting photo gallery access allows the user to upload any picture from their photo gallery, you can safely deny photo gallery access for this Service.</li>
                            </ul>
                        </section>

                        <section>
                            <h3>4. How We Use The Information We Collect</h3>
                            <p>
                                Any of the information we collect from you may be used in one of the following ways:
                            </p>
                            <ul>
                                <li><strong>To personalize your experience:</strong> your information helps us to better respond to your individual needs</li>
                                <li><strong>To improve our service:</strong> we continually strive to improve our service offerings based on the information and feedback we receive from you</li>
                                <li><strong>To improve customer service:</strong> your information helps us to more effectively respond to your customer service requests and support needs</li>
                                <li><strong>To process transactions:</strong> Your information, whether public or private, will not be sold, exchanged, transferred, or given to any other company for any reason whatsoever, without your consent, except for the express purpose of delivering the purchased product or service requested.</li>
                                <li><strong>To administer a contest, promotion, survey or other site feature.</strong></li>
                                <li><strong>To send periodic emails:</strong> The email address you provide for order processing, may be used to send you information and updates pertaining to your order, in addition to receiving occasional company news, updates, related product or service information, etc.</li>
                            </ul>
                        </section>

                        <section>
                            <h3>5. When do we use customer information from third parties?</h3>
                            <p>
                                We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a Fliphats customer, we receive information from a third party that provides automated fraud detection services to Fliphats. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
                            </p>
                        </section>

                        <section>
                            <h3>6. Do we share the information we collect with third parties?</h3>
                            <p>
                                We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.
                            </p>
                            <p>
                                We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the website, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the website. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.
                            </p>
                            <p>
                                We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the website in a shared location, and type of the device used to visit the website. They may aggregate information about our advertising and what you see on the website and then provide auditing, research and reporting for us and our advertisers.
                            </p>
                            <p>
                                We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.
                            </p>
                        </section>

                        <section>
                            <h3>7. Where and when is information collected from customers and end users?</h3>
                            <p>
                                Fliphats will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above. By using the Service, you signify your acceptance of this Privacy Policy. If you do not agree to this policy, please do not use our Service. Your continued use of the Service following the posting of changes to this policy will be deemed your acceptance of those changes.
                            </p>
                        </section>

                        <section>
                            <h3>8. How Long Do We Keep Your Information?</h3>
                            <p>
                                We keep your information only so long as we need it to provide Fliphats to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can't identify you.
                            </p>
                        </section>

                        <section>
                            <h3>9. How We Protect Your Information</h3>
                            <p>
                                We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to Fliphats or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.
                            </p>
                        </section>

                        <section>
                            <h3>10. Governing Law</h3>
                            <p>
                                This Privacy Policy is governed by the laws of Australia without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.
                            </p>
                            <p>
                                The laws of Australia, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the website may also be subject to other local, state, national, or international laws.
                            </p>
                        </section>

                        <section>
                            <h3>11. Your Consent</h3>
                            <p>
                                By using our Fliphats, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.
                            </p>
                        </section>

                        <section>
                            <h3>12. Links to Other Websites</h3>
                            <p>
                                This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by Fliphats. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
                            </p>
                        </section>

                        <section>
                            <h3>13. Cookies</h3>
                            <p>
                                Fliphats uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
                            </p>
                        </section>

                        <section>
                            <h3>14. Blocking and disabling cookies and similar technologies</h3>
                            <p>
                                Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information.
                            </p>
                        </section>

                        <section>
                            <h3>15. Contact Us</h3>
                            <p>
                                Don't hesitate to contact us if you have any questions.
                            </p>
                            <ul>
                                <li>Via Email: info@fliphats.com</li>
                                <li>Via Phone Number: +61 400 000 000</li>
                                <li>Via this Link: https://fliphats.com/contact</li>
                            </ul>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    );
}
