import { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export const metadata: Metadata = {
    title: 'Terms of Service - Fliphats',
    description: 'Terms of Service for the Fliphats platform.',
};

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background">
            {/* Navigation Header */}
            <nav className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
                <div className="max-w-5xl mx-auto px-6 h-14 flex items-center justify-between">
                    <Link href="/login" className="flex items-center gap-2 text-sm font-medium text-muted-foreground transition-colors hover:text-primary">
                        <ArrowLeft className="h-4 w-4" />
                        Back to Login
                    </Link>
                    <div className="font-semibold text-sm">Fliphats Legal</div>
                </div>
            </nav>

            <div className="py-16 px-6 sm:px-10">
                <div className="max-w-3xl mx-auto">
                    <div className="text-center mb-16">
                        <h1 className="text-4xl font-bold tracking-tight mb-4">Terms of Service</h1>
                        <p className="text-muted-foreground">Last Updated: January 25, 2026</p>
                    </div>

                    <div className="prose prose-zinc dark:prose-invert max-w-none space-y-12">
                        <section>
                            <h3>1. General Terms</h3>
                            <p>
                                By accessing and placing an order with Fliphats, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Fliphats.
                            </p>
                            <p>
                                Under no circumstances shall Fliphats team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Fliphats team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.
                            </p>
                            <p>
                                Fliphats will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.
                            </p>
                        </section>

                        <section>
                            <h3>2. License</h3>
                            <p>
                                Fliphats grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.
                            </p>
                            <p>
                                These Terms & Conditions are a contract between you and Fliphats (referred to in these Terms & Conditions as "Fliphats", "us", "we" or "our"), the provider of the Fliphats website and the services accessible from the Fliphats website (which are collectively referred to in these Terms & Conditions as the "Fliphats Service").
                            </p>
                            <p>
                                You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the Fliphats Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.
                            </p>
                        </section>

                        <section>
                            <h3>3. Definitions and Key Terms</h3>
                            <p>
                                To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, they are strictly defined as:
                            </p>
                            <ul>
                                <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                                <li><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Fliphats, which is responsible for your information under this Terms & Conditions.</li>
                                <li><strong>Country:</strong> where Fliphats or the owners/founders of Fliphats are based, in this case is Australia.</li>
                                <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Fliphats and use the services.</li>
                                <li><strong>Service:</strong> refers to the service provided by Fliphats as described in the relative terms (if available) and on this platform.</li>
                                <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                                <li><strong>Website:</strong> Fliphats’s site, which can be accessed via this URL: fliphats.com</li>
                                <li><strong>You:</strong> a person or entity that is registered with Fliphats to use the Services.</li>
                            </ul>
                        </section>

                        <section>
                            <h3>4. Restrictions</h3>
                            <p>You agree not to, and you will not permit others to:</p>
                            <ul>
                                <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website or make the platform available to any third party.</li>
                                <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.</li>
                                <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Fliphats or its affiliates, partners, suppliers or the licensors of the website.</li>
                            </ul>
                        </section>

                        <section>
                            <h3>5. Your Suggestions</h3>
                            <p>
                                Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to Fliphats with respect to the website shall remain the sole and exclusive property of Fliphats.
                            </p>
                            <p>
                                Fliphats shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.
                            </p>
                        </section>

                        <section>
                            <h3>6. Your Consent</h3>
                            <p>
                                We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.
                            </p>
                        </section>

                        <section>
                            <h3>7. Links to Other Websites</h3>
                            <p>
                                This Terms & Conditions applies only to the Services. The Services may contain links to other websites not operated or controlled by Fliphats. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.
                            </p>
                        </section>

                        <section>
                            <h3>8. Cookies</h3>
                            <p>
                                Fliphats uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.
                            </p>
                        </section>

                        <section>
                            <h3>9. Changes To Our Terms & Conditions</h3>
                            <p>
                                You acknowledge and agree that Fliphats may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at Fliphats’s sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform Fliphats when you stop using the Service. You acknowledge and agree that if Fliphats disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.
                            </p>
                            <p>
                                If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.
                            </p>
                        </section>

                        <section>
                            <h3>10. Modifications to Our website</h3>
                            <p>
                                Fliphats reserves the right to modify, suspend or discontinue, temporarily or permanently, the website or any service to which it connects, with or without notice and without liability to you.
                            </p>
                        </section>

                        <section>
                            <h3>11. Updates to Our website</h3>
                            <p>
                                Fliphats may from time to time provide enhancements or improvements to the features/ functionality of the website, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates").
                            </p>
                            <p>
                                Updates may modify or delete certain features and/or functionalities of the website. You agree that Fliphats has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the website to you.
                            </p>
                            <p>
                                You further agree that all Updates will be (i) deemed to constitute an integral part of the website, and (ii) subject to the terms and conditions of this Agreement.
                            </p>
                        </section>

                        <section>
                            <h3>12. Third-Party Services</h3>
                            <p>
                                We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").
                            </p>
                            <p>
                                You acknowledge and agree that Fliphats shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Fliphats does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.
                            </p>
                            <p>
                                Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.
                            </p>
                        </section>

                        <section>
                            <h3>13. Term and Termination</h3>
                            <p>
                                This Agreement shall remain in effect until terminated by you or Fliphats.
                            </p>
                            <p>
                                Fliphats may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.
                            </p>
                            <p>
                                This Agreement will terminate immediately, without prior notice from Fliphats, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the website and all copies thereof from your computer.
                            </p>
                            <p>
                                Upon termination of this Agreement, you shall cease all use of the website and delete all copies of the website from your computer.
                            </p>
                            <p>
                                Termination of this Agreement will not limit any of Fliphats's rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.
                            </p>
                        </section>

                        <section>
                            <h3>14. Copyright Infringement Notice</h3>
                            <p>
                                If you are a copyright owner or such owner’s agent and believe any material on our website constitutes an infringement on your copyright, please contact us setting forth the following information: (a) a physical or electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the material that is claimed to be infringing; (c) your contact information, including your address, telephone number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and (e) the a statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.
                            </p>
                        </section>

                        <section>
                            <h3>15. Indemnification</h3>
                            <p>
                                You agree to indemnify and hold Fliphats and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the website; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.
                            </p>
                        </section>

                        <section>
                            <h3>16. No Warranties</h3>
                            <p>
                                The website is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, Fliphats, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the website, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, Fliphats provides no warranty or undertaking, and makes no representation of any kind that the website will meet your requirements, achieve any intended results, be compatible or work with any other software, websites, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.
                            </p>
                            <p>
                                Without limiting the foregoing, neither Fliphats nor any Fliphats's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the website, or the information, content, and materials or products included thereon; (ii) that the website will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the website; or (iv) that the website, its servers, the content, or e-mails sent from or on behalf of Fliphats are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.
                            </p>
                            <p>
                                Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.
                            </p>
                        </section>

                        <section>
                            <h3>17. Limitation of Liability</h3>
                            <p>
                                Notwithstanding any damages that you might incur, the entire liability of Fliphats and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the website.
                            </p>
                            <p>
                                To the maximum extent permitted by applicable law, in no event shall Fliphats or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the website, third-party software and/or third-party hardware used with the website, or otherwise in connection with any provision of this Agreement), even if Fliphats or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.
                            </p>
                            <p>
                                Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.
                            </p>
                        </section>

                        <section>
                            <h3>18. Severability</h3>
                            <p>
                                If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.
                            </p>
                            <p>
                                This Agreement, together with the Privacy Policy and any other legal notices published by Fliphats on the Services, shall constitute the entire agreement between you and Fliphats concerning the Services. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and Fliphats’s failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. YOU AND Fliphats AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.
                            </p>
                        </section>

                        <section>
                            <h3>19. Waiver</h3>
                            <p>
                                Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not effect a party's ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach.
                            </p>
                            <p>
                                o failure to exercise, and no delay in exercising, on the part of either party, any right or any power under this Agreement shall operate as a waiver of that right or power. Nor shall any single or partial exercise of any right or power under this Agreement preclude further exercise of that or any other right granted herein. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern.
                            </p>
                        </section>

                        <section>
                            <h3>20. Amendments to this Agreement</h3>
                            <p>
                                Fliphats reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.
                            </p>
                            <p>
                                By continuing to access or use our website after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Fliphats.
                            </p>
                        </section>

                        <section>
                            <h3>21. Entire Agreement</h3>
                            <p>
                                The Agreement constitutes the entire agreement between you and Fliphats regarding your use of the website and supersedes all prior and contemporaneous written or oral agreements between you and Fliphats.
                            </p>
                            <p>
                                You may be subject to additional terms and conditions that apply when you use or purchase other Fliphats's services, which Fliphats will provide to you at the time of such use or purchase.
                            </p>
                        </section>

                        <section>
                            <h3>22. Updates to Our Terms</h3>
                            <p>
                                We may change our Service and policies, and we may need to make changes to these Terms so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to these Terms and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Terms. If you do not want to agree to these or any updated Terms, you can delete your account.
                            </p>
                        </section>

                        <section>
                            <h3>23. Intellectual Property</h3>
                            <p>
                                The website and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by Fliphats, its licensors or other providers of such material and are protected by Australia and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. The material may not be copied, modified, reproduced, downloaded or distributed in any way, in whole or in part, without the express prior written permission of Fliphats, unless and except as is expressly provided in these Terms & Conditions. Any unauthorized use of the material is prohibited.
                            </p>
                        </section>

                        <section>
                            <h3>24. Contact Us</h3>
                            <p>
                                Don't hesitate to contact us if you have any questions.
                            </p>
                            <ul>
                                <li>Via Email: info@fliphats.com</li>
                                <li>Via Phone Number: +61 400 000 000</li>
                                <li>Via this Link: https://fliphats.com/contact</li>
                            </ul>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    );
}
