ALTER TABLE customers
ADD COLUMN fb_lead_id VARCHAR(255),
ADD COLUMN fb_created_time DATETIME,
ADD COLUMN ad_id VARCHAR(255),
ADD COLUMN ad_name VARCHAR(255),
ADD COLUMN adset_id VARCHAR(255),
ADD COLUMN adset_name VARCHAR(255),
ADD COLUMN campaign_id VARCHAR(255),
ADD COLUMN form_id VARCHAR(255),
ADD COLUMN form_name VARCHAR(255),
ADD COLUMN is_organic BOOLEAN DEFAULT FALSE,
ADD COLUMN platform VARCHAR(50),
ADD COLUMN fb_lead_status VARCHAR(50);
